In [1]:
'''np.random.rand(): Floats from a uniform distribution [0,1) excluding 1'''

import numpy as np

np.random.rand(10)
np.random.rand(2,2)
np.random.rand(10, 10)

array([[0.23199389, 0.20143274, 0.99860853, 0.28116533, 0.34572873,
        0.31316396, 0.04700596, 0.68046601, 0.28252495, 0.37725858],
       [0.41841595, 0.43655217, 0.95822468, 0.23793809, 0.70472672,
        0.50269008, 0.3122884 , 0.56558282, 0.27878828, 0.68449116],
       [0.93010888, 0.83252277, 0.09725749, 0.18021006, 0.37021337,
        0.25874027, 0.41963916, 0.18045614, 0.76187069, 0.01539229],
       [0.84192586, 0.31707943, 0.73643362, 0.55568685, 0.54521292,
        0.94144509, 0.76376188, 0.37700339, 0.14456514, 0.61284278],
       [0.1059418 , 0.88127387, 0.57759284, 0.57289801, 0.95029277,
        0.6198558 , 0.31818499, 0.88879041, 0.36786589, 0.4819554 ],
       [0.35572515, 0.49211866, 0.08878067, 0.18070522, 0.35063061,
        0.70709554, 0.58664586, 0.4211867 , 0.02892749, 0.29478899],
       [0.87462341, 0.31473914, 0.80044618, 0.8817333 , 0.02636072,
        0.80365529, 0.65965035, 0.9637792 , 0.67332183, 0.98009566],
       [0.9478566 , 0.31325079, 0.8150953

In [2]:
'''np.random.randn(): Returns random values in a standard normal 
distribution mean = 0 and std = 1(Standard gaussian Distribution)
mean = 0
standard deviation = 1'''
import numpy as np

np.random.randn(3,3,3)
np.random.randn(3,2,2)




array([[[ 1.49368374,  0.38565586],
        [-1.59561587,  1.07984422]],

       [[-1.27520827,  1.33935758],
        [-0.87536764, -1.42672613]],

       [[ 0.90047739,  0.63654383],
        [ 0.75841579, -0.20438446]]])

In [3]:
'''np.random.normal(): Returns samples from normal distribution
loc : mean of the distribution (by default = 0)
scale: standard deviation(default = 1)
size :shape of the output array'''
import numpy as np
np.random.normal( loc = 0, scale = 1, size = (3,3))

array([[-2.08104107,  0.4469986 , -3.07420063],
       [-1.16022839, -1.55128632,  1.85193852],
       [-0.99788677, -2.27171385, -0.58225512]])

In [4]:
'''np.random.random() OR np.random.sample():
Return random numbers from 0.0 to 1.0'''


'np.random.random() OR np.random.sample():\nReturn random numbers from 0.0 to 1.0'

In [5]:
'''np.random.uniform(): generates numbrs in uniform range (low, high)'''

import numpy as np

np.random.uniform(1, 200, 20)

array([134.15492608,  79.27406667,  77.31233014,  40.06606299,
        76.98064353,  11.01631726, 193.27721664, 123.42145086,
        86.89147606,  72.69362638, 168.88728962, 178.01279828,
        43.5930031 ,  64.46820641,  60.87154037, 132.68754687,
        59.95170039,  24.43478254, 160.07801461,  73.29285717])

In [6]:
import  numpy as np

np.random.uniform(1, 500, (2, 2))

array([[230.29246278,  67.73094437],
       [209.46756905, 235.06709601]])

In [7]:
import pandas as pd
import numpy as np
array = np.array([1,2,3,4,5])
s = pd.Series(array)
#s * 2
s ** 2

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [8]:
import pandas as pd
import numpy as np

array1 = np.array([11,22,33,44,55])
array2 = np.array([12,14,16])

s1 = pd.Series(array1)
s2 = pd.Series(array2)

s = s1+s2

s.fillna(0)

0    23.0
1    36.0
2    49.0
3     0.0
4     0.0
dtype: float64

In [9]:
import pandas as pd
import numpy as np

array1 =np.array([1,2,3,4,np.nan])
array2 = np.array([11,22,np.nan,33,np.nan])

s1 = pd.Series(array1)
s2 = pd.Series(array2)

s = s1.fillna(0) + s2.fillna(0)
s.head()


0    12.0
1    24.0
2     3.0
3    37.0
4     0.0
dtype: float64

In [10]:
import pandas as pd
import numpy as np
dict = {'marks' : [60, 75,82,69, np.nan, np.nan]}
s = pd.Series(dict)
series = s.fillna(0)
series.head()


marks    [60, 75, 82, 69, nan, nan]
dtype: object