NumPy:
------

NumPy is Numerical Python simply means fundamental library for numerical computations.
It provide support for array, mathematical functions, linear algebra and more.

->numpy is a powerful library for numerical operations.
->It support for multi-dimensional array and matrices
->it offers efficient mathematical functions and operations

We represent list in square brackets[],
We also represent numpy in square brackets[],
Soo what is the difference between numpy array and list?


performance--->	List					        NumPy
		Slower because it is more		        Faster because it uses fixed data types
		flexible to store heterogeneous
		data types

Memory Efficiency->List					        NumPy
		used more memory because it stores	    more memory efficient because it uses 
		refrences to objects			        contiguous memery block

datatype-->	list					            NUMPY
		can store different datatypes		    can store same datatype, require all datatypes tobe same

functionality->	

    lacks built-in support for mathematic	    it is support for  mathematic computations, 
	computations                                boardcasting and vectorized computations

Indexing & slicing->

    Support basic indexing and slicing	        support advanced indexing and slicing



creating an array in NumPy:

to create a numpy array we need to do is import a NumPy library and give a alias to a numpy library like

---> import NumPy as np  #here numpy is the library and np is the alias name we have given.

to create a numpy array we use 

array(): is a function used to createNumPy array from a Python list.

syntax:

numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

	object: Any array-like structure (list, tuple, or another NumPy array).

	dtype: Data type of array elements (e.g., int, float, complex).

	copy: Whether to copy the input data (True by default).

	order: Memory layout (C for row-major, F for column-major).

	subok: Whether to allow subclasses (False by default).

	ndmin: Minimum number of dimensions.


Properties of NumPy array:

ndim: returns the number of dimention of numpy array
shape: return the shape of array return number of rows and columns, sape(rows, columns)
size: return the number of element.
dtype: return the datatype of elements.


In [1]:
import numpy as np

array = np.array([[1,2,3,4,5], [2,4,6,8,10]])
#print properties of numpy array

print(array.ndim) #number of dimentions - 2
print(array.shape) #shape of the given array shape(rows, columns) (2,5)
print(array.size) #Number of elements - 10
print(array.dtype) # the datatype of given array - int64

2
(2, 5)
10
int64


zeros() : it will create a array filled with zero's.

syntax:

np.zeros(shape, dtype = float, order = 'c')

Parameter this function will take:
	shape: tuple or int which defines the shape of the array.
	dtype: the datatype of elements by default will be float
	order: memory layout('C' for row_major and 'F' for column_major


In [4]:
array1= np.zeros(0) #it will create a one dimention array with zeros.

array2 = np.zeros((5,5)) # it will create 5 * 5 array with zeros.

array3_int = np.zeros((2,3), dtype = int) #it will create a two dimention array with int type of elements

array4 = np.zeros((2,3,4)) #it will create a #D array with two blocks, three rows and four columns.


why am i creating array with zeros?

---> Initialization or memory allocation


one(): this function creates array filled with ones.

syntax:

np.ones(shape, dtype : float, order = 'c')

Parameter this function will take:
	shape: tuple or int which defines the shape of the array.
	dtype: the datatype of elements by default will be float
	order: memory layout('C' for row_major and 'F' for column_major)

In [5]:
import numpy as np

arr = np.ones((5, 5))
array = np.ones((5,5), dtype = int) #explicit convertion float to int

print(arr)
print(array)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


why we create a array or multi-dimentional array with 1:

---->   You need a default value (instead of zeros).

	You want to initialize weights, biases, or matrices in machine learning.

	You are preparing an array for multiplication or normalization.

we have created array with 0's nd 1'n what if we wanted to create array with different numbers?


full(): fill array with specific value given by the user. if we want to create array with fixed size we can use full().

syntax:

np.full(shape, fill_value, dtype = None, order = 'C')

parameter:	shape: tuple which specifies the dimension
		fill_value: the value to fill array with.
		dtype: (optional) datatype of array(int or float)
		order: (optional) memory layout.


In [6]:
import numpy as np

array = np.full((5,5), 8) #fills array with 8.

print(array)


[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


eye(): feate a identity matrix of two dimension.

syntax:

numpy.eye(N, M=None, k=0, dtype=float, order='C')

parameters: 	N → Number of rows

		M → (Optional) Number of columns (default: same as N, making it square)

		k → (Optional) Shift for the diagonal (default: 0)

		dtype → (Optional) Data type (int, float, etc.)

		order → (Optional) Memory layout ('C' for row-major, 'F' for column-major)


In [7]:
import numpy as np

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


arrange() : It will create a array with range of values.

syntax:

np.arrange(start, end, step, dtype = None)

parameters:	start : a starting pointer from where array is going to start, bydefault it will be 0.
		end : the end value, mandatory 
		step : increment between two values.
		dtype: it is optional



In [8]:
arr = np.arange(1, 10, 2)
print(arr)


[1 3 5 7 9]


linspace(): Generates evenly spaced numbers.

syntax:

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

parameters:	start → The starting value.

	stop → The ending value.

	num → (Optional) The number of values to generate (default: 50).

	endpoint → (Optional) Whether to include the stop value (default: True).

	retstep → (Optional) If True, returns the step size used.

	dtype → (Optional) The data type of the array.

In [9]:
#the difference between elemnts in 2.25.
import numpy as np
arr = np.linspace(1, 10, num=5) #createa array with equally spaced elements
print(arr)


[ 1.    3.25  5.5   7.75 10.  ]


Indexing and Slicing:


In [10]:
import numpy as np

array = np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]])

print(array[0:]) #returns 0th index to end of the index
print(array[1:]) #returns 1th index to end of the index
print(array[2:]) #returns 2nd index
print(array[0:2]) #returns elements excluding 0th index elements

print(array[:-1]) #excludes -1 index and return remaining elemts
print(array[:-2]) #excludes -2 only returnd remaining index
print(array[:-3]) #return empty array cause there are no element in -4 index.

print(array[0,0]) #returns value ot first row and first column.
print(array[-1,-1]) #law rowm last column
print(array[-2,-2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]
[]
1
12
7


Mathamatical Operations:


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5, 7, 9]
print(a - b)  # [-3, -3, -3]
print(a * b)  # [4, 10, 18] (Element-wise multiplication)
print(a / b)  # [0.25, 0.4, 0.5]

print(np.sqrt(a))    # Square root
print(np.exp(a))     # Exponential
print(np.log(a))     # Natural log
print(np.sum(a))     # Sum of all elements
print(np.mean(a))    # Mean (average)
print(np.std(a))     # Standard deviation

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
6
2.0
0.816496580927726


Reshaping and Flattening(1D): Converts dimentions of arrat to given or 1d array.


In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr_reshaped = arr.reshape((3, 2))  # Change shape to (3,2)
arr_flattened = arr.flatten()       # Convert to 1D array

print(arr_reshaped)
print(arr_flattened)



[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


Broadcasting: Allows multiplication between array of different shapes.


In [13]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

print(a + b)  # Adds b to each row of a
print(a - b)
print(a * b)
print(a / b)
print(a // b)



[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]
[[1 1 1]
 [4 2 2]]


Linear Algebra in NumPy:


In [14]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication
print(np.linalg.inv(A))  # Inverse of A
print(np.linalg.det(A))  # Determinant of A
print(np.linalg.eig(A))  # Eigenvalues and eigenvectors



[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


Random Numbers with NumPy: generate random numbers in given range.


In [15]:
import numpy as np


print(np.random.rand(3, 3))    # Random values in [0, 1]
print(np.random.randint(1, 10, (2, 2))) # Random integers
print(np.random.randn(3, 3))   # Standard normal distribution
print(np.random.choice([10, 20, 30]))  # Random choice from a list

[[0.21881063 0.03441511 0.86633324]
 [0.82586657 0.7425366  0.68300104]
 [0.7587523  0.39702894 0.12315078]]
[[9 2]
 [8 6]]
[[-0.09055493 -0.36933063 -2.2905822 ]
 [-0.65921761  1.01501376 -0.21492787]
 [-0.91550692  0.48716149  0.69843673]]
20


random.rand():  numpy.random.rand() in NumPy is function numpy.random.rand() generates random numbers between 0 and 1 from a uniform distribution.


In [16]:
import numpy as np

arr = np.random.rand()
print(arr)

arr1 = np.random.rand(5)  # generates 5 random numbers
print(arr1)

arr2 = np.random.rand(3, 4)  # generates 3 rows, 4 columns with random numbers between 0 to 1
print(arr2)


0.3307050605509373
[0.79324857 0.86222172 0.31096355 0.60089203 0.11489808]
[[5.14357746e-01 3.62935255e-01 7.53449725e-01 1.96847791e-01]
 [5.39997218e-01 6.81429407e-02 4.47031120e-04 1.67751845e-01]
 [5.20107993e-01 3.32245063e-01 8.03456418e-02 6.67140705e-02]]


numpy.random.randint(): The function  generates random integer values from a specified range.


In [18]:
import numpy as np

arr = np.random.randint(1, 10)  # Random integer between 1 and 9
print(arr)

arr = np.random.randint(1, 10, size=5)  # Generate array of 5 random integers
print(arr)

arr = np.random.randint(1, 10, size=(3, 4))  # generate 2d array of 3 rows, 4 columns
print(arr)

arr = np.random.randint(1, 100, size=5, dtype=np.int32) #returns Datatype 
print(arr.dtype) 



4
[6 2 4 5 6]
[[6 4 8 4]
 [8 7 2 7]
 [2 1 5 7]]
int32
